apiVersion: apps/v1
kind: Deployment
metadata:
  name: deleteme
  labels:
    version: v1
    app: deleteme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deleteme
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: deleteme
      annotations:
        kubernetes.io/change-cause: "Image updated to %IMAGE_VERSION%"
    spec:
      containers:
      - name: deleteme
        image: "davismar98/deleteme:%IMAGE_VERSION%"
        ports:
        - containerPort: 8080