apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-sre-challenge-v1
  labels:
    version: v1
    app: api-sre-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-sre-challenge
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: api-sre-challenge
    spec:
      containers:
      - name: api-sre-challenge
        image: davismar98/api-sre-challenge:a9baa12
        ports:
        - containerPort: 8080