---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %SRE_PROJECT_NAME%
  labels:
    app: %SRE_PROJECT_NAME%
spec:
  replicas: 2
  selector:
    matchLabels:
      app: %SRE_PROJECT_NAME%
  template:
    metadata:
      labels:
        app: %SRE_PROJECT_NAME%
      annotations:
        kubernetes.io/change-cause: "Image updated to %IMAGE_VERSION%"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - name: %SRE_PROJECT_NAME%
        image: "davismar98/%SRE_PROJECT_NAME%:%IMAGE_VERSION%"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: "250Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1