---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: %SRE_PROJECT_NAME%
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: %SRE_PROJECT_NAME%
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60