---
apiVersion: v1
kind: Service
metadata:
  name: %SRE_PROJECT_NAME%
  labels:
    app: %SRE_PROJECT_NAME%
spec:
  type: NodePort
  selector:
    app: %SRE_PROJECT_NAME%
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000